import type { CSSProperties } from "react";
import type { ProductScanResult } from "@foodtrace/shared";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "grid",
    gridTemplateColumns: "1.1fr 0.9fr",
    gap: 24,
    padding: 32,
    background: "radial-gradient(circle at top, #0f5d49 0%, #08131b 45%, #05070a 100%)",
    color: "#f4f4ef",
    fontFamily: "Inter, system-ui, sans-serif",
  },
  hero: {
    padding: 28,
    borderRadius: 28,
    background: "rgba(7, 17, 22, 0.7)",
    border: "1px solid rgba(255,255,255,0.1)",
  },
  kicker: {
    margin: 0,
    letterSpacing: 3,
    textTransform: "uppercase",
    opacity: 0.7,
  },
  title: {
    fontSize: 56,
    lineHeight: 1.02,
    maxWidth: 560,
    margin: "16px 0",
  },
  body: {
    maxWidth: 580,
    fontSize: 18,
    lineHeight: 1.6,
    opacity: 0.88,
  },
  roleGrid: {
    marginTop: 32,
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
  },
  rolePill: {
    padding: "12px 16px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.18)",
    background: "transparent",
    color: "#f4f4ef",
    cursor: "pointer",
  },
  roleActive: {
    padding: "12px 16px",
    borderRadius: 999,
    border: "1px solid #c4f1db",
    background: "#c4f1db",
    color: "#12392d",
    cursor: "pointer",
  },
  card: {
    padding: 24,
    borderRadius: 28,
    background: "linear-gradient(135deg, #182620 0%, #11161b 60%)",
    border: "1px solid rgba(255,255,255,0.08)",
    alignSelf: "start",
  },
  demoCard: {
    gridColumn: "1 / -1",
    padding: 24,
    borderRadius: 28,
    background: "rgba(17, 22, 27, 0.92)",
    border: "1px solid rgba(196,241,219,0.18)",
  },
  demoHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
    marginBottom: 18,
  },
  demoTitle: {
    margin: "8px 0 0",
    fontSize: 28,
  },
  demoPassword: {
    padding: "10px 12px",
    borderRadius: 999,
    background: "rgba(196,241,219,0.12)",
    border: "1px solid rgba(196,241,219,0.26)",
    color: "#c4f1db",
    fontWeight: 700,
  },
  demoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: 12,
  },
  demoItem: {
    display: "grid",
    gap: 12,
    alignContent: "space-between",
    padding: 16,
    borderRadius: 18,
    background: "#0d1216",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  demoName: {
    margin: 0,
    color: "#f4f4ef",
    fontWeight: 800,
  },
  demoMeta: {
    margin: "6px 0 0",
    color: "#a9c7b8",
    fontSize: 13,
  },
  demoPurpose: {
    margin: "8px 0 0",
    color: "rgba(244,244,239,0.76)",
    lineHeight: 1.45,
  },
  demoCodeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 18,
    marginTop: 22,
  },
  demoSubTitle: {
    margin: "0 0 10px",
    color: "#f4f4ef",
  },
  demoCodeButton: {
    display: "grid",
    gap: 4,
    minWidth: 190,
    padding: "12px 14px",
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "#192027",
    color: "#f4f4ef",
    textAlign: "left",
    cursor: "pointer",
  },
  segmented: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
    marginBottom: 20,
  },
  segment: {
    padding: 14,
    borderRadius: 16,
    background: "#192027",
    color: "#f4f4ef",
    border: "1px solid rgba(255,255,255,0.08)",
    cursor: "pointer",
  },
  segmentActive: {
    padding: 14,
    borderRadius: 16,
    background: "#c4f1db",
    color: "#12392d",
    border: "1px solid #c4f1db",
    cursor: "pointer",
  },
  form: {
    display: "grid",
    gap: 14,
  },
  label: {
    display: "grid",
    gap: 8,
    fontSize: 14,
    color: "rgba(244,244,239,0.85)",
  },
  input: {
    padding: "14px 16px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "#0d1216",
    color: "#f4f4ef",
    outline: "none",
  },
  primaryButton: {
    padding: "14px 16px",
    borderRadius: 16,
    border: "none",
    background: "#77c7a2",
    color: "#062014",
    fontWeight: 700,
    cursor: "pointer",
  },
  secondaryButton: {
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "transparent",
    color: "#f4f4ef",
    fontWeight: 600,
    cursor: "pointer",
  },
  status: {
    marginTop: 18,
    marginBottom: 0,
    color: "#a9c7b8",
  },
  signedIn: {
    display: "grid",
    gap: 14,
  },
  userRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 999,
    display: "grid",
    placeItems: "center",
    background: "#c4f1db",
    color: "#12392d",
    fontWeight: 800,
    letterSpacing: 0.5,
    flex: "0 0 auto",
  },
  userMeta: {
    minWidth: 0,
    flex: "1 1 auto",
  },
  userName: {
    margin: 0,
    color: "#f4f4ef",
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  userSub: {
    margin: 0,
    marginTop: 4,
    color: "rgba(169,199,184,0.9)",
    textTransform: "capitalize",
    fontSize: 13,
  },
  scanCard: {
    gridColumn: "1 / -1",
    padding: 28,
    borderRadius: 28,
    background: "linear-gradient(135deg, #17352a 0%, #10161b 55%)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  foodCard: {
    gridColumn: "1 / -1",
    padding: 28,
    borderRadius: 28,
    background: "linear-gradient(135deg, #17352a 0%, #10161b 55%)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  scanKicker: {
    margin: 0,
    textTransform: "uppercase",
    letterSpacing: 2.5,
    color: "#93b9ac",
  },
  scanTitle: {
    marginTop: 12,
    fontSize: 32,
    marginBottom: 8,
  },
  scanBody: {
    margin: 0,
    maxWidth: 680,
    lineHeight: 1.6,
    color: "#b4c3be",
  },
  scanInputRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: 12,
    marginTop: 20,
  },
  foodButtons: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 20,
  },
  foodFormGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
    marginTop: 20,
  },
  scanInput: {
    padding: "14px 16px",
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "#0b0f13",
    color: "#f4f4ef",
  },
  sampleRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 14,
  },
  sampleButton: {
    padding: "10px 14px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "#182028",
    color: "#ecf2ef",
    cursor: "pointer",
  },
  linkButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "10px 14px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "#182028",
    color: "#ecf2ef",
    cursor: "pointer",
    textDecoration: "none",
    fontSize: 14,
  },
  resultCard: {
    marginTop: 18,
    padding: 20,
    borderRadius: 24,
    background: "linear-gradient(135deg, #14251d 0%, #0b0f13 60%)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  qrCard: {
    marginTop: 18,
    padding: 20,
    borderRadius: 24,
    background: "#0b0f13",
    border: "1px solid rgba(119,199,162,0.35)",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 18,
    alignItems: "center",
  },
  qrImage: {
    width: 180,
    height: 180,
    borderRadius: 18,
    background: "#fff",
    padding: 10,
    objectFit: "contain",
  },
  badge: {
    display: "inline-flex",
    padding: "8px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 14,
  },
  resultTitle: {
    margin: "0 0 8px",
    fontSize: 28,
  },
  resultSummary: {
    margin: 0,
    color: "#c5d1cd",
    lineHeight: 1.6,
  },
  resultGrid: {
    marginTop: 18,
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 14,
  },
  action: {
    marginTop: 18,
    color: "#dce7e2",
    fontWeight: 600,
  },
  weatherCard: {
    marginTop: 18,
    padding: 20,
    borderRadius: 24,
    background: "linear-gradient(135deg, #173a2c 0%, #0b0f13 65%)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  weatherNow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
    flexWrap: "wrap",
    gap: 12,
  },
  weatherTemp: {
    fontSize: 40,
    fontWeight: 800,
    color: "#f4f4ef",
    margin: 0,
  },
  weatherCondition: {
    color: "#77c7a2",
    fontSize: 14,
    margin: "4px 0 0",
  },
  weatherStatsCol: {
    display: "grid",
    gap: 4,
    justifyItems: "end",
    color: "#a9c7b8",
    fontSize: 13,
  },
  weatherForecastRow: {
    display: "flex",
    gap: 10,
    marginTop: 18,
    overflowX: "auto",
    paddingBottom: 4,
  },
  weatherDayTile: {
    flex: "0 0 auto",
    minWidth: 84,
    padding: 12,
    borderRadius: 16,
    background: "#0d1216",
    border: "1px solid rgba(255,255,255,0.08)",
    textAlign: "center",
  },
  weatherDayLabel: { color: "#8fa39a", fontSize: 12, margin: "0 0 6px" },
  weatherDayTemp: { color: "#f4f4ef", fontSize: 14, fontWeight: 700, margin: 0 },
  weatherDayRain: { color: "#5CA8E0", fontSize: 11, margin: "4px 0 0" },
};

export function scanBadgeStyle(status: ProductScanResult["status"]): CSSProperties {
  const palette: Record<ProductScanResult["status"], CSSProperties> = {
    safe: { ...styles.badge, background: "#c4f1db", color: "#12392d" },
    caution: { ...styles.badge, background: "#f6e7b5", color: "#594400" },
    recalled: { ...styles.badge, background: "#f7c2c2", color: "#7a1b1b" },
    not_found: { ...styles.badge, background: "#d1d5db", color: "#25303b" },
  };
  return palette[status];
}
